export const user = {
    login: 'test',
    id: 513010,
    node_id: 'MDQ6VXNlcjUxMzAxMA==',
    avatar_url: 'https://avatars2.githubusercontent.com/u/513010?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/test',
    html_url: 'https://github.com/test',
    followers_url: 'https://api.github.com/users/test/followers',
    following_url: 'https://api.github.com/users/test/following{/other_user}',
    gists_url: 'https://api.github.com/users/test/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/test/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/test/subscriptions',
    organizations_url: 'https://api.github.com/users/test/orgs',
    repos_url: 'https://api.github.com/users/test/repos',
    events_url: 'https://api.github.com/users/test/events{/privacy}',
    received_events_url: 'https://api.github.com/users/test/received_events',
    type: 'User',
    site_admin: false,
    score: 1,
};
